### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by avivace** [bbbbbr/gbtoolsid#2]
would it be possible to have the output in a JSON format so it's easy to be parsed?

**Comment by bbbbbr** [comment]
Try `-oj` (json style output). Let me know if it needs any improvements. I added it early on but didn't test it much.

I think I'm also overdue to add detection for new GBDK releases and some other (very old) music drivers. But might still be a month or two before I get to those.

Edit: There are also two forms of CSV output:
```
-oc  : csv style output
-oC  : Bare csv style output (no field names)
```

**Comment by avivace** [comment]
Working as expected, thanks!
